services:
  alina-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alina-bot-local
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      TZ: Asia/Krasnoyarsk
      MANUAL_LOCK_BYPASS_CHAT_IDS: ${MANUAL_LOCK_BYPASS_CHAT_IDS:-u2i-nX_MNQKx6XjXiqeH6hNFAA}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
